title: Babacar GUEYE - CV
profile_img: /assets/img/profile.webp
icon_img: /assets/img/icon.webp

name: "Babacar GUEYE"
job: "〈Data Analyst / Architect〉"

phone_number: +33(0)669-766-714
address: Paris, France
email: gueye.babacar@outlook.com
linkedin_username: gueyeb
github_username: gueyeb
# instagram_username: instagram
# twitter_username: twitter
# facebook_username: facebook
# youtube_username: youtube
blog_url: https://gueyeb.github.io/

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl:

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag