# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Blog
tagline:          'Babacar Gueye'
description:      'Some news from <a href="https://twitter.com/babttz">@me</a>.'
url:              http://blog.babacar-gueye.fr

author:
  name:           'Babacar GUEYE'
  url:            https://twitter.com/gueyeb
  email:	  gueyens11@gmail.com

paginate:         5

# Custom vars

github: gueyeb
twitter: babttz
instagram:

# Settings for comments helper
# Set 'provider' to the comment provider you want to use.
# Set 'provider' to false to turn commenting off globally.
#
comments:
  provider: disqus
  disqus:
    short_name : gueyeb-blog
  livefyre :
    site_id : 123
  intensedebate :
    account : 123abc
  facebook :
    appid : 123
    num_posts: 5
    width: 580
    colorscheme: light

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#        
analytics :
  provider : google
  google : 
      tracking_id : 'UA-50044273-1'
  getclicky :
    site_id :